### ISSUE TITLE
Meeting notes?

### ISSUE THREAD

**Issue by geerlingguy** [drud/sig-drupal#1]
It might be nice to have a place where we store/save meeting notes / meeting agendas. I already wanted to reference something from our Wednesday call but I'm forgetting it :D

**Comment by geerlingguy** [comment]
Ah, just noticed the meeting notes are linked in the meeting area...

**Comment by cyberswat** [comment]
Thanks for the suggestion.  It looks like this is resolved, but for anyone that might have the same problem the meeting minutes [are linked](https://docs.google.com/document/d/17NoYKJe0iV46r6yARBtwaTetTlXgZpiAyITWydoiR8w/edit#) from the README in this repository.  The first paragraph in the minutes also links to video recordings of each of the meetings we don't mess up.
