### ISSUE TITLE
Access to drupal.slack.com

### ISSUE THREAD

**Issue by aroq** [drud/sig-drupal#3]
Hello,

Sorry for creating this request here, but I didn't find a better way.

I'd like to participate in this SIG, how I can gain access to the group?

Thank you in advance for your help!

Regards.

**Comment by rfay** [comment]
Hi @aroq  - Signing up for Drupal slack is described at https://www.drupal.org/slack - Basically you just sign up at http://drupalslack.herokuapp.com/

Then when you are in Drupal slack, just join the #kubernetes channel. 

Feel free to follow up here if you have any trouble with that, sorry for the slow response. You can also contact me on slack as "rfay", happy to help you there.

**Comment by aroq** [comment]
hey @rfay 

Thank you for your help, much appreciated!
